### ISSUE TITLE
Song Selection UI

### ISSUE THREAD

**Issue by Caleb618** [ronnoc536/Capstone-2#20]
User Story:
As a user of the app, I want to be able to see all of my songs so that I can choose one to listen to.

Acceptance Test:
If the user is logged into the client app, when they are on the song selection screen, then they should be able to scroll through their uploaded songs.

**Comment by Thaysen01** [comment]
Created a basic implementation of this using code from Movies. The column count was removed to allow for 1 long bar featuring the song. Old UI file linked for reference

[oldMusicSelection.ui.txt](https://github.com/user-attachments/files/17169044/oldMusicSelection.ui.txt)
