### ISSUE TITLE
Host App Database

### ISSUE THREAD

**Issue by Caleb618** [ronnoc536/Capstone-2#5]
User Story:
As someone with a large collection of movies, books, and music, I want to be able to store my media collection in a central location so that I can keep everything together.

Acceptance Test:
If the user is logged into the host app, when they upload media, then it should be stored in a database.

**Comment by ronnoc536** [comment]
A core info table has been added. This just includes title, type, and id.

**Comment by ronnoc536** [comment]
added some more metadata for each of the types, need to work on relearning how to hierarchy databases and make things stack and reference one another 4ab3c0d26f83e096c6c30617464ac5efde419bb6
